### use pipeline template from Gitlab
include:
  - project: "bu-f-ps/infra/pipeline-templates"
    file: "/zendesk/theme.yml"

variables:
  ZCLI_VERSION: "1.0.0-beta.56"
  NODE_VERSION: "25.9.0"
  APPROVE_FOR_PROJECT: "fps_skc_pe"
  ### Set this temporary during pipelines debug for prevent actual deploy/rollback in PROD
  DRY_RUN: "true"
